### PR TITLE
Cherry pick + refactor fix for #1812 from branch fix-7.2.5

### LINKED ISSUE #1812: Material networks creation in 7.2.4 is slower than before
**Describe the bug**
Since version 7.2.4 the creation of material networks is slower than it was in 7.2.3, the time can be multiplied by an order of magnitude. This happens only in the hydra render delegate.

**To Reproduce**
1. Install 7.2.3.x and 7.2.4.x 
2. Use a profiler and render in a hydra enabled application both version

### PR DESCRIPTION
**Pull request by cpichard**
**Changes proposed in this pull request**
- Add the fix related to issue #1812 coming from the branch fix-7.2.5. This is the fix to optimise/limit the calls to the AiMaterialx functions

**Issues fixed in this pull request**
Fixes #1812

### CODE REVIEW

**Review by sebastienblor — APPROVED** [review]

File: libs/common/api_adapter.h [hunk 1]
```diff
@@ -136,8 +138,43 @@ class ArnoldAPIAdapter {
...
+        return shaderNodeEntryIt->second;
+    };
+
+    AtString GetCachedOslCode(const std::string &oslCodeKey, const char *nodeDefinition, AtParamValueMap *params) {
+        std::lock_guard<AtMutex> lock(_oslCodeCacheMutex);
+        const auto oslCodeIt = _oslCodeCache.find(oslCodeKey);
+        if (oslCodeIt == _oslCodeCache.end()) {
+    #if ARNOLD_VERSION_NUM > 70104
+            _oslCodeCache[oslCodeKey] = AiMaterialxGetOslShaderCode(nodeDefinition, "shader", params);
+    #elif ARNOLD_VERSION_NUM >= 70104
```
Comment (BigRoy) [inline libs/common/api_adapter.h:161]: Is this the correct version number being compared against? It looks odd that it's comparing to the same value - basically this else statement says after the `if` says `ARNOLD_VERSION_NUM == 70104` right?

It also means that if the version would be `< 70104` this `if` statement body would effectively be empty?

Comment (sebastienblor) [reply libs/common/api_adapter.h:161]: Yes, before Arnold 7.1.4 this API didn't exist and there was no way to get any osl code, so it won't render this shader.
In 7.1.4 the API was first introduced, and in following versions an argument was added. So that's why we have the current ifdefs. Indeed it would have behaved the same way if it had been written `elif ARNOLD_VERSION_NUM == 70104`

Comment (BigRoy) [reply libs/common/api_adapter.h:161]: Thanks, makes sense. 👍
