### PR TITLE
Fixing testsuite issues using 21.02+ and supporting new and old light parameter naming conventions.

### LINKED ISSUE #772: Testsuite fails when using USD 21.05/21.02
**Describe the bug**
There are failures when running the testsuite using USD 21.05 or 21.02, I suspect these happen due to the changes in light token names, as most of the failures due to lighting differences

**To Reproduce**
1. Build/run the testsuite using USD 21.05.

**Expected behavior**
Testsuite runs clean.

### LINKED ISSUE #880: Scenes using pre-21.02 light parameters are not rendering correctly
**Describe the bug**
USD files exported from applications using an older version of USD won't work correctly in the procedural, due to the light parameter name changes in 21.02 and 21.05.

### PR DESCRIPTION
**Pull request by sirpalee**
**Changes proposed in this pull request**
- Supporting both new and old light parameter naming conventions, without using the UsdLux APIs.
- Changing tests 140 and 181, so we make sure the new parameters are preferred over the old ones.
- Fixing test 15 with 21.08.
- Adding support for animated color temperature.

**Issues fixed in this pull request**
Fixes #880
Fixes #772

**Additional context**
I benchmarked the new code vs the old code, using the worst possible case: when no parameters are set we are checking both the new and old parameter names. The results were: 1-3 seconds when translating 1 million UsdLux lights to Arnold primitives on a single thread. This means about 1-3 microseconds of overhead for each light, which seems acceptable.

In scenes with many lights (above 10k), we have significant other overheads than just 10ms+ introduced in this PR.

### CODE REVIEW

**Review by sebastienblor — APPROVED** [review]

File: translator/reader/read_light.cpp [hunk 1]
```diff
@@ -36,63 +37,118 @@
...
+{
+    if (attr.HasAuthoredConnections()) {
+        return attr;
+    } else {
+        auto oldAttr = light.GetPrim().GetAttribute(oldName);
+        return oldAttr && oldAttr.HasAuthoredConnections() ? oldAttr : attr;
+    }
+}
+
+#if 1
```
Comment (jhodgson) [inline translator/reader/read_light.cpp:97]: We can remove the unused case here.
