### PR TITLE
Ensure we don't map/unmap empty arrays

### LINKED ISSUE #1502: Render delegate crashes with empty arrays
Some scenes having empty primvar arrays end up crashing arnold when rendered in Hydra.

### PR DESCRIPTION
**Pull request by sebastienblor**
**Changes proposed in this pull request**
This PR ensures that we don't call AiArrayMap / AiArrayUnmap with empty arrays, which can happen sometimes when primvars are empty arrays.

**Issues fixed in this pull request**
Fixes #1502

### CODE REVIEW

File: render_delegate/basis_curves.cpp [hunk 1]
```diff
@@ -198,12 +200,14 @@ void HdArnoldBasisCurves::Sync(
                     } else if (desc.value.IsHolding<VtVec3fArray>()) {
                         const auto& v = desc.value.UncheckedGet<VtVec3fArray>();
                         auto* arr = AiArrayAllocate(v.size(), 1, AI_TYPE_VECTOR2);
-                        std::transform(
-                            v.begin(), v.end(), static_cast<GfVec2f*>(AiArrayMap(arr)),
-                            [](const GfVec3f& in) -> GfVec2f {
-                                return {in[0], in[1]};
-                            });
-                        AiArrayUnmap(arr);
+                        if (!v.empty()) {
```
Comment (cpichard) [inline render_delegate/basis_curves.cpp:203]: question ... would `if (AiArrayGetDataSize(arr)) {` also work ? in case the allocation failed ...

**Review by cpichard — DISMISSED** [review]
lgtm, an additional note in the changelog would be fantastic

File: render_delegate/basis_curves.cpp (hunk 1 above)
Comment (sebastienblor) [reply render_delegate/basis_curves.cpp:203]: maybe, but since we explicitely set 1 key, the issue should only happen if v.size is 0, so it should be equivalent

**Review by cpichard — APPROVED** [review]
